# pylint: disable=too-few-public-methods
from abc import ABC, abstractmethod

class FileGenerator(ABC):
    """Generate a file in the given output directory using the given params"""
    @abstractmethod
    def __call__(self, output_directory, params):
        """
        Parameters
        ----------
        output_directory : str
          Directory to store the generated file in

        params : dict
          Dictionary of parameters.

        Returns
        -------
        paths : { str : str }
          Map from generator type to generated file paths
        """

    @abstractmethod
    def relative_out_path(self):
        """
        Returns
        -------
        The relative path generated by the file generator
        """

    @abstractmethod
    def sub_dir(self, path=None):
        """Sub directory to use when generating the file.

        Parameters
        ----------
        path : Path-like or None
          Relative path.

        Returns
        -------
        current_sub_dir : Path
        """
